# Generated by Django 5.2.4 on 2025-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_updated_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urls',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
