# Generated by Django 5.2.4 on 2025-07-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_urls_of_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinidea',
            old_name='ai_description',
            new_name='pin_description',
        ),
        migrations.RenameField(
            model_name='pinidea',
            old_name='ai_title',
            new_name='pin_title',
        ),
    ]
